### PR TITLE
Compute Domain Separator on Every Run

### PR DESCRIPTION
**Pull request by nlordell**
This PR computes the domain separator on every settlement instead of using a pre-computed constant. This is to avoid issues if the chain ID changes sometime in the future (like in EthPoW after the merge).

### Test Plan

CI continues to pass, and:
```
% npm run -s bench # Before:
gas used: 16507

% npm run -s bench # After:
gas used: 16708
```

### CODE REVIEW

**Review by fleupold — APPROVED** [review]
Up to you if you want to merge this or not (I think the gas overhead is small, but I also understand you argument that since the settlement's contract separator is fixed and it is easy to redeploy this contract it doesn't make a lot of sense to change this here)

**Review by fedgiac — APPROVED** [review]
In the previous month we had ~20k settlements. This means that (at current gas prices & eth value) we'd pay ~100$/month to make sure that signatures for this contract cannot be replayed when used in a fork of Ethereum. In terms of being worth it is really borderline.

**Comment by nlordell** [comment]
I thought about this a bit more, and I think it makes sense to include. Otherwise, we may accidentally allow for settlements to be replayed across networks if we forget to remove the trampoline as a solver.

**Comment by nlordell** [comment]
Will merge on top of #14.

**Pull request merged**
